apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: micro-twitter
type: Opaque
stringData:
  DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/micro_twitter"
  JWT_SECRET: "your-super-secret-jwt-key-change-in-production-k8s"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "micro_twitter"
